version: '3'
services:
  app:
    build: frontend
    ports:
      - "8080:8080"
    environment: 
      - PRODUCTS_URL=http://products:8080
      - PORT=8080
  products:
    build: product-api
    environment:
      - PORT=8080