steps:
- name: gcr.io/cloud-builders/docker
  args: ['build',
  '-t', 'gcr.io/$PROJECT_ID/product',
  '.',
  ]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/product"]
- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run", "deploy", "product",
      "--image","gcr.io/$PROJECT_ID/product",
      "--platform","managed",
      "--region", "us-central1",
      "--no-allow-unauthenticated",
    ]
images: ['gcr.io/$PROJECT_ID/product']
timeout: 3600s